1.How does a feed forward network with a multi layer perceptron architecture solve the xor problem
2.How does a feed forward network handle multi class classification task and what are the key steps involved in propagating input data through the network to produce class probabilities using activation func like soft max

In [ ]:
import numpy as np
def relu(x):
  return max(0,x)
def tn(x):
  return np.tanh(x)

In [ ]:
i1=int(input("enter the number:"))
i2=int(input("enter the number:"))

weights={'w11':0.3,'w12':0.3,'w21':0.2,'w22':0.2,'w31':0.5,'w32':0.5}
h1=i1*weights['w11']+i2*weights['w21']
h2=i1*weights['w12']+i2*weights['w22']

h1_act=relu(h1)
h2_act=relu(h2)

o1=h1_act*weights['w31']+h2_act*weights['w32']
o1_act=tn(o1)


print(int(bool(o1_act)))

enter the number:1
enter the number:1
1


In [ ]:
import pandas as pd
def relu(x):
  return np.maximum(0,x)
def sigmoid(x):
  return (1/(1+np.exp(-x)))
def softmax(x):
  l=[]
  for i in h:
    l.append(np.exp(i))
  return l/sum(l)


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

df=pd.read_csv('/content/titanic.csv')
df.drop(columns=['PassengerId','Pclass','Survived','Parch','SibSp'],inplace=True)
df.fillna({'Age':df['Age'].mean(),'Fare':df['Fare'].mean()},inplace=True)
df['Embarked']=df['Embarked'].map({'Q':0,'S':1,'C':2})
df['Sex']=df['Sex'].map({'male':0,'female':1})

features = ['Sex', 'Age', 'Fare']
X = df[features].values
y = df['Embarked'].values
s = StandardScaler()
X_scaled = s.fit_transform(X)
weights = [[0.59348704, 0.40109883, 0.28617046],[0.82291927, 0.17715662, 0.1684946],[0.34189922, 0.12574664, 0.83438127]]
weights_o=[[0.14195772, 0.97765211, 0.83343769],
 [0.79167686, 0.69152006, 0.64352697],
 [0.41410903, 0.66399141, 0.50717641]]
print(weights_o)
h= np.dot(X_scaled, weights)
h_act=sigmoid(h)
o=np.dot(h,weights_o)
o_act=softmax(o)

predicted_classes = np.argmax(o_act, axis=1)
df['predicted'] = predicted_classes

print(df[['Embarked', 'predicted']])
print(confusion_matrix(df['predicted'],df['Embarked']))

[[0.14195772, 0.97765211, 0.83343769], [0.79167686, 0.69152006, 0.64352697], [0.41410903, 0.66399141, 0.50717641]]
     Embarked  predicted
0           0          1
1           1          0
2           0          0
3           1          1
4           1          1
..        ...        ...
413         1          1
414         2          0
415         1          1
416         1          1
417         2          1

[418 rows x 2 columns]
[[  2  23  23]
 [ 44 245  73]
 [  0   2   6]]
